# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodeType: "delegate"       # should be one of "delegate", "full_node", and "lightweight"

# this doesn't matter since p2p layer is overrun by simulator
network:
    addr: "INIT BY CODE"
    msgLogsCleaningInterval: 2s
    msgLogRetention: 10s
    healthCheckInterval: 1s
    silentInterval: 5s
    peerMaintainerInterval: 1s
    allowMultiConnsperIP: true
    numPeersLowerBound: 6
    numPeersUpperBound: 12
    pingInterval: 1s
    rateLimitEnabled: false
    rateLimitPerSec: 5
    rateLimitWindowSize: 60s
    bootstrapNodes:
    maxMsgSize: 10485760
    peerDiscovery: true
    ttl: 3
    bootstrapNodes:
        - "node1"
        - "node2"

chain:
    chainDBPath: "../chain.db"
    trieDBPath: "../trie.db"
    producerPrivKey: "925f0c9e4b6f6d92f2961d01aff6204c44d73c0b9d0da188582932d4fcad0d8ee8c66600"
    producerPubKey: "336eb60a5741f585a8e81de64e071327a3b96c15af4af5723598a07b6121e8e813bbd0056ba71ae29c0d64252e913f60afaeb11059908b81ff27cbfa327fd371d35f5ec0cbc01705"
    inMemTest: false

consensus:
    scheme: "ROLLDPOS"
    rollDPoS:
        delegateInterval: 1ms
        proposerInterval: 0ms
        unmatchedEventTTL: 1000s
        roundStartTTL: 1000s
        acceptProposeTTL: 1000s
        acceptPrevoteTTL: 1000s
        acceptVoteTTL: 1000s
        delay: 5s
        eventChanSize: 10000
        numSubEpochs: 1
        proposerCB: "PseudoRotatedProposer"
        epochCB: "PseudoStarNewEpoch"
    blockCreationInterval: 1000s

blockSync:
    interval: 70ms

delegate:
    addrs:
        - "INIT BY CODE"

dispatcher:
    eventChanSize: 1024

actPool:
    maxNumActPerPool: 32768
    maxNumActPerAcct: 2048
    eventChanSize: 1024